[package]
name = "portal-bridge"
description = "Bridge node for the Portal Network"
authors.workspace = true
categories.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
alloy.workspace = true
anyhow.workspace = true
async-trait.workspace = true
chrono.workspace = true
clap.workspace = true
delay_map.workspace = true
discv5.workspace = true
e2store.workspace = true
eth_trie.workspace = true
ethereum_ssz.workspace = true
ethportal-api.workspace = true
futures.workspace = true
humanize-duration.workspace = true
itertools.workspace = true
jsonrpsee = { workspace = true, features = [
  "async-client",
  "client",
  "macros",
  "server",
] }
portalnet.workspace = true
prometheus_exporter.workspace = true
rand.workspace = true
reqwest.workspace = true
reqwest-middleware = { workspace = true, features = ["json"] }
reqwest-retry = { workspace = true }
revm.workspace = true
revm-primitives.workspace = true
scraper.workspace = true
serde = { workspace = true, features = ["rc"] }
serde_json.workspace = true
serde_yaml.workspace = true
ssz_types.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
trin-evm.workspace = true
trin-execution.workspace = true
trin-metrics.workspace = true
trin-utils.workspace = true
trin-validation.workspace = true
url.workspace = true

[dev-dependencies]
env_logger.workspace = true
rstest.workspace = true
test-log.workspace = true
tracing-test.workspace = true
