[package]
name = "trin-core"
version = "0.1.0"
edition = "2021"
rust-version = "1.56.1"

[dependencies]
async-trait = "0.1.51"
base64 = "0.13.0"
clap = "2.33.3"
ctrlc = "3.1.8"
directories = "3.0"
env_logger = "0.8.2"
eth2_ssz = "0.4.0"
eth2_ssz_derive = "0.3.0"
eth2_ssz_types = "0.2.1"
ethers-core = "0.6.0"
futures = "0.3.13"
hex = "0.4.3"
httparse = "1.5.1"
lazy_static = "1.4.0"
log = "0.4.14"
rand = "0.8.4"
rlp = "0.5.0"
rocksdb = "0.16.0"
rstest = "0.11.0"
serde = {version = "1.0.125", features = ["derive"] }
serde_json = "1.0.59"
stunclient = "0.1.2"
structopt = "0.3"
sha3 = "0.9.1"
thiserror = "1.0.29"
threadpool = "1.8.1"
tokio = {version = "1.8.0", features = ["full"]}
tokio-test = "0.4.2"
tokio-util = "0.6.8"
tracing = "0.1.26"
tracing-futures = "0.2.5"
uint = { version = "0.8.5", default-features = false }
ureq = {version = "2.2.0", features = ["json"]}
url = "2.2.2"
validator = { version = "0.13.0", features = ["derive"] }

[target.'cfg(windows)'.dependencies]
ethers-providers = { version = "0.6.0", default-features = false, features = ["ws", "rustls"] }
ipconfig = "0.2.2"
uds_windows = "1.0.1"

[target.'cfg(unix)'.dependencies]
ethers-providers = "0.6.0"
interfaces = "0.0.7"

[dependencies.discv5]
branch = "fewer-mutable-borrows"
git = "https://github.com/carver/discv5"

[dependencies.rusqlite]
version = "0.25.3"
features = ["bundled"]
