[package]
name = "trin-validation"
description = "Validation layer for the Portal Network data."
authors.workspace = true
categories.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
alloy.workspace = true
anyhow.workspace = true
enr = "0.13.0"
ethereum_hashing = "0.7.0"
ethereum_ssz.workspace = true
ethereum_ssz_derive.workspace = true
ethportal-api.workspace = true
lazy_static.workspace = true
rust-embed.workspace = true
serde.workspace = true
serde_json.workspace = true
ssz_types.workspace = true
tokio.workspace = true
tree_hash.workspace = true
tree_hash_derive.workspace = true

[dev-dependencies]
quickcheck.workspace = true
quickcheck_macros = "1.0.0"
rstest.workspace = true
serde_yaml.workspace = true
trin-utils.workspace = true
