[package]
name = "utp-testing"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.52"
jsonrpsee = {version = "0.15.1", features = ["full"]}
rand = "0.8.5"
structopt = "0.3.26"
utp = { version = "0.1.0-alpha", git = "https://github.com/jacobkaufmann/utp.git", branch = "conn-x" }
tracing = "0.1.36"
tracing-subscriber = "0.3.15"
trin-core = { path = "../trin-core" }
tokio = {version = "1.8.0", features = ["full"]}
discv5 = "0.1.0"
hex = "0.4.3"

[[bin]]
name = "utp-test-app"
path = "src/bin/test_app.rs"

[[bin]]
name = "utp-test-suite"
path = "src/bin/test_suite.rs"
