[package]
name = "utp-testing"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.52"
tracing = "0.1.26"
tracing-subscriber = "0.2.18"
trin-core = { path = "../trin-core" }
tokio = {version = "1.8.0", features = ["full"]}
discv5 = { git = "https://github.com/sigp/discv5.git", branch = "master" }
hex = "0.4.3"
log = "0.4.14"
lru = "0.7.7"
parking_lot = "0.11.2"
