[package]
name = "utp-testing"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing = "0.1.26"
tracing-subscriber = "0.2.18"
trin-core = { path = "../trin-core" }
tokio = {version = "1.8.0", features = ["full"]}
discv5 = "0.1.0-beta.13"
hex = "0.4.3"
log = "0.4.14"
