[package]
name = "utp-testing"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.52"
jsonrpsee = {version = "0.15.1", features = ["full"]}
structopt = "0.3.26"
tracing = "0.1.26"
tracing-subscriber = "0.2.18"
trin-core = { path = "../trin-core" }
tokio = {version = "1.8.0", features = ["full"]}
discv5 = { git = "https://github.com/sigp/discv5.git", branch = "master" }
hex = "0.4.3"
log = "0.4.14"

[[bin]]
name = "utp-testing"
path = "src/bin/local_test.rs"

[[bin]]
name = "utp-test-app"
path = "src/bin/test_app.rs"

[[bin]]
name = "utp-test-suite"
path = "src/bin/test_suite.rs"
