[package]
name = "trin-validation"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/ethereum/trin/tree/main/trin-validation"
license = "GPL-3.0"
readme = "README.md"
keywords = ["ethereum", "portal-network"]
categories = ["cryptography::cryptocurrencies"]
description = "Validation layer for the Portal Network data."
authors = ["https://github.com/ethereum/trin/graphs/contributors"]

[dependencies]
anyhow = "1.0.68"
async-trait = "0.1.53"
eth2_hashing = "0.2.0"
eth2_ssz = "0.4.0"
eth2_ssz_derive = "0.3.0"
eth2_ssz_types = "0.2.1"
ethereum-types = "0.12.1"
ethportal-api = { path = "../ethportal-api" }
lazy_static = "1.4.0"
serde = { version = "1.0.150", features = ["derive"] }
serde_json = "1.0.89"
tokio = { version = "1.14.0", features = ["full"] }
tree_hash = "0.4.0"
tree_hash_derive = "0.4.0"
trin-types = { path = "../trin-types" }
trin-utils = { path = "../trin-utils" }

[dev-dependencies]
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"
rlp = "0.5.0"
rstest = "0.11.0"
