[package]
name = "trin-utils"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/ethereum/trin/tree/main/trin-utils"
license = "GPL-3.0"
readme = "README.md"
keywords = ["ethereum", "portal-network"]
categories = ["cryptography::cryptocurrencies"]
description = "Utils library for Trin."
authors = ["https://github.com/ethereum/trin/graphs/contributors"]
build = "build.rs"

[dependencies]
anyhow = "1.0.68"
discv5 = { version = "0.2.1", features = ["serde"] }
hex = "0.4.3"
serde_json = {version = "1.0.89", features = ["preserve_order"]}
trin-types = { path = "../trin-types" }

[dev-dependencies]
rstest = "0.11.0"
