[package]
name = "trin-storage"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/ethereum/trin/tree/master/trin-storage"
license = "GPL-3.0"
readme = "README.md"
keywords = ["ethereum", "portal-network"]
categories = ["cryptography::cryptocurrencies"]
description = "Storage library for Trin."
authors = ["https://github.com/ethereum/trin/graphs/contributors"]

[dependencies]
anyhow = "1.0.68"
discv5 = { version = "0.4.0", features = ["serde"] }
ethereum-types = "0.14.1"
ethportal-api = {path = "../ethportal-api"}
r2d2 = "0.8.9"
r2d2_sqlite = "0.19.0"
rusqlite = { version = "0.26.3", features = ["bundled"] }
strum = { version = "0.26.1", features = ["derive"] }
thiserror = "1.0.29"
tracing = "0.1.36"
trin-metrics = { path = "../trin-metrics" }
