[package]
name = "ethportal-api"
version = "0.1.2"
edition = "2021"
description = "Definitions for various Ethereum Portal Network JSONRPC APIs"
license = "GPL-3.0"
repository = "https://github.com/ethereum/trin/tree/master/ethportal-api"

[dependencies]
bytes = "1.3.0"
enr = {version= "0.7.0", features=["serde", "ed25519"]}
ethereum-types = "0.12.1"
ethnum = "1.3.2"
eth_trie = "0.1.0"
eth2_ssz = "0.4.0"
eth2_ssz_derive = "0.3.0"
eth2_ssz_types = "0.2.1"
hex = "0.4.3"
hex-literal = "0.3.4"
jsonrpsee = {version="0.16.2", features = ["macros"]}
rlp = "0.5.1"
rlp-derive = "0.1.0"

keccak-hash = "0.10.0"
serde = { version = "1.0.150", features = ["derive"] }
serde-hex = "0.1.0"
sha2 = "0.10.1"

[dev-dependencies]
rstest = "0.16.0"
serde_json = "1.0.89"

[features]
default = ["client"]
client = ["jsonrpsee/client", "jsonrpsee/async-client"]
server = ["jsonrpsee/server"]
