[package]
name = "trin-state"
description = "State network subprotocol for Trin."
authors.workspace = true
categories.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
alloy = { workspace = true, features = ["getrandom"] }
anyhow.workspace = true
cpu-time = "1.0.0"
discv5.workspace = true
eth_trie.workspace = true
ethportal-api.workspace = true
keccak-hash.workspace = true
parking_lot.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
trin-portalnet.workspace = true
trin-storage.workspace = true
trin-validation.workspace = true
utp-rs.workspace = true

[dev-dependencies]
env_logger.workspace = true
rstest.workspace = true
serde.workspace = true
serde_yaml.workspace = true
serial_test.workspace = true
test-log.workspace = true
tracing-subscriber.workspace = true
trin-utils.workspace = true
